import Head from 'next/head'
import { Button, Flex, Text } from '@chakra-ui/react'
import Footer from '@/components/Footer/Footer'

export default function About() {
  return (
    <>
      <Head>
        <title>Rollsolid | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDirection="column"  width="100%">
        <Flex height="720px">
          <Text>Hi</Text>
        </Flex>
        <Footer />
      </Flex>
    </>
  )
}
