import Head from 'next/head'
import { Button, Flex, Text } from '@chakra-ui/react'

export default function About() {
  return (
    <>
      <Head>
        <title>Rollsolid | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex px={4} py={4}>
        <Text>Hi</Text>
      </Flex>
    </>
  )
}
