import React from 'react';
import Head from 'next/head';
import { Flex, Text } from '@chakra-ui/react';
import { auth } from '@/firebase/clientApp';
import { useAuthState } from 'react-firebase-hooks/auth';
import { useEffect } from 'react';
import router from 'next/router';

export default function Dashboard() {

    const [user, loading, error] = useAuthState(auth);

    useEffect(() => {
        if (!user) {
            router.push('/login');
        }
    }, [user]);

    if (loading) {
        return (
            <Text>Loading</Text>
        );
    } else if (error) {
        return (
            <Text>Error occurred</Text>
        );
    } else if (!user) {
        return (
            <Text
                color='red.300'
                fontSize="16pt"
            >
Unauthorized Access
            </Text>
        );
    }

    return (
        <>
            <Head>
                <title>Rollsolid | Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <Flex
                px={4}
                py={4}
            >
                <Text>Secret dashboard</Text>
            </Flex>
        </>
    );
}
