import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Button, Flex, Text } from '@chakra-ui/react'
import Window from '../components/Window/Window'

import Draggable from 'react-draggable'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Rollsolid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex>
        <Window>
          <Text>Select the two cards that you were dealt to view probabilities</Text>
        </Window>
      </Flex>
    </>
  )
}
