import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Button, Flex, Text } from '@chakra-ui/react'
import Window from '../components/Window/Window'

import Draggable from 'react-draggable'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Login() {
  const [render, setRender] = useState(true);
  return (
    <>
      <Head>
        <title>Rollsolid | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex px={4} py={4}>
        <Window render={render} setRender={setRender}>
          <Text>Login</Text>
        </Window>
      </Flex>
    </>
  )
}
