import React from 'react';
import Head from 'next/head';
import { Flex, Text } from '@chakra-ui/react';
import { useEffect } from 'react';
import { useAuthState } from 'react-firebase-hooks/auth';
import { auth } from '../firebase/clientApp';
import router from 'next/router';
import ProfileView from '@/components/Settings/ProfileView';

export default function Profile() {
    const [user, loading, error] = useAuthState(auth);

    useEffect(() => {
        if (!user && !loading) {
            router.push('/login');
        }
    }, [user]);

    if (loading) {
        return (
            <Text>Loading</Text>
        );
    } else if (error) {
        return (
            <Text>Error occurred</Text>
        );
    } else if (!user) {
        router.push('/login');
        return (
            <Text
                color='red.300'
                fontSize="16pt"
            >
              Unauthorized Access
            </Text>
        );
    }

    return (
        <>
            <Head>
                <title>Rollsolid | Profile</title>
                <meta 
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <Flex>
                <ProfileView />
            </Flex>
        </>
    );
}
