import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Button, Flex, Text } from '@chakra-ui/react'
import Window from '../components/Window/Window'

import Draggable from 'react-draggable'
import { useState } from 'react'
import UserSignUp from '@/components/Auth/UserSignUp'

const inter = Inter({ subsets: ['latin'] })

export default function SignUp() {
  const [render, setRender] = useState(true);
  return (
    <>
      <Head>
        <title>Rollsolid | Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex px={4} py={4}>
        <UserSignUp />
      </Flex>
    </>
  )
}
